<?php
namespace Wiakowe\Tests\CsvReader\Header;

use Wiakowe\CsvReader\Header\CsvHeader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-18 at 10:36:38.
 */
class CsvHeaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CsvHeader
     */
    protected $object;
    protected $headerCell;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->headerCell = \Mockery::mock(
            '\Wiakowe\CsvReader\Header\CsvHeaderCell'
        );

        $this->headerCell->shouldReceive('getName')
            ->andReturn('header1');

        $this->headerCell->shouldReceive('getColumn->getColumnPosition')
            ->andReturn(1);

        $this->object = new CsvHeader(array($this->headerCell));
    }

    /**
     * @covers Wiakowe\CsvReader\Header\CsvHeader::getNumHeaders
     */
    public function testGetNumHeaders()
    {
        $this->assertEquals(1, $this->object->getNumHeaders(),
            'The number of headers should be one.');
    }

    /**
     * @covers Wiakowe\CsvReader\Header\CsvHeader::getHeaderCellByName
     */
    public function testGetHeaderCellByName()
    {
        $this->assertSame(
            $this->headerCell,
            $this->object->getHeaderCellByName('header1'),
            'The header returned should be the same as the set one.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\Header\CsvHeader::getHeaderCellByPosition
     */
    public function testGetHeaderCellByPosition()
    {
        $this->assertSame(
            $this->headerCell,
            $this->object->getHeaderCellByPosition(1),
            'The header returned should be the same as the set one.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\Header\CsvHeader::getHeaderCellByName
     *
     * @expectedException \Wiakowe\CsvReader\Exception\CellNotFoundException
     */
    public function testGetHeaderCellByNameThrowsException()
    {
        $this->object->getHeaderCellByName('header2');
    }

    /**
     * @covers Wiakowe\CsvReader\Header\CsvHeader::getHeaderCellByPosition
     *
     * @expectedException \Wiakowe\CsvReader\Exception\CellNotFoundException
     */
    public function testGetHeaderCellByPositionThrowsException()
    {
        $this->object->getHeaderCellByPosition(2);
    }

    /**
     * @covers Wiakowe\CsvReader\Header\CsvHeader::__construct
     * @covers Wiakowe\CsvReader\Header\CsvHeader::getHeaderCells
     */
    public function testGetHeaderCells()
    {
        $this->assertContains(
            $this->headerCell,
            $this->object->getHeaderCells(),
            'The array should contain the set header.'
        );
    }
}
