<?php
namespace Wiakowe\Tests\CsvReader\File;

use Wiakowe\CsvReader\File\CsvFile;
use org\bovigo\vfs\vfsStream;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-18 at 11:20:59.
 */
class CsvFileTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CsvFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $dir = vfsStream::setup('root');
        $csv = vfsStream::newFile('file.csv');

        $dir->addChild($csv);

        $csv->setContent(
<<<CSVCONTENT
"header1", "header2"
"row1",1
"row2",2
"row3",3
CSVCONTENT
        );

        $this->object = new CsvFile(vfsStream::url('root/file.csv'));
    }

    public function testConstruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    public function testConstructNotReadableFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::hasHeader
     * @todo   Implement testHasHeader().
     */
    public function testHasHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::totalRows
     */
    public function testTotalRows()
    {
        $this->assertEquals(3, $this->object->totalRows());
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::totalColumns
     */
    public function testTotalColumns()
    {
        $this->assertEquals(2, $this->object->totalColumns());
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getRow
     */
    public function testGetRow()
    {
        $row = $this->object->getRow(1);

        $this->assertInstanceOf('\Wiakowe\CsvReader\Row\CsvRow', $row);

        $this->assertEquals(1, $row->getRowPosition());
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getColumn
     */
    public function testGetColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getCell
     * @todo   Implement testGetCell().
     */
    public function testGetCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getRowIterator
     * @todo   Implement testGetRowIterator().
     */
    public function testGetRowIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
