<?php
namespace Wiakowe\Tests\CsvReader\File;

use Wiakowe\CsvReader\File\CsvFile;
use org\bovigo\vfs\vfsStream;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-18 at 11:20:59.
 */
class CsvFileTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CsvFile
     */
    protected $object;
    protected $filePath;
    protected $csvFile;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $dir = vfsStream::setup('root');
        $this->csvFile = vfsStream::newFile('file.csv');

        $dir->addChild($this->csvFile);

        $this->csvFile->setContent(
<<<CSVCONTENT
"header1", "header2"
"row1",1
"row2",2
"row3",3
CSVCONTENT
        );
        $this->filePath = vfsStream::url('root/file.csv');

        $this->object = new CsvFile($this->filePath);
    }

    public function testConstruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    public function testConstructNotReadableFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::hasHeader
     */
    public function testHasHeader()
    {
        $this->assertTrue($this->object->hasHeader(),
            'By default the object is believed to have a header.');

        $csvFile = new CsvFile($this->filePath, false);

        $this->assertFalse($csvFile->hasHeader(),
            'Has header has to be false if it\'s value is overridden.');
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getHeader
     */
    public function testGetHeader()
    {
        $header = $this->object->getHeader();

        $this->assertInstanceOf('\Wiakowe\CsvReader\Header\CsvHeader', $header);

        $this->assertEquals(2, $header->getNumHeaders());

        $this->assertTrue(
            $header->getHeaderCellByName('header1') &&
                $header->getHeaderCellByName('header2'),
            'Headers must be found for header1 and header2.');
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::totalRows
     */
    public function testTotalRows()
    {
        $this->assertEquals(3, $this->object->totalRows());
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::totalColumns
     */
    public function testTotalColumns()
    {
        $this->assertEquals(2, $this->object->totalColumns());
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getRow
     */
    public function testGetRow()
    {
        $row = $this->object->getRow(1);

        $this->assertInstanceOf('\Wiakowe\CsvReader\Row\CsvRow', $row);

        $this->assertEquals(1, $row->getRowPosition());
    }

    public function testGetRowThrowsRowNotFoundException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getColumn
     */
    public function testGetColumnByPosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getColumn
     */
    public function testGetColumnByHeaderCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getColumn
     */
    public function testGetColumnThrowsColumnNotFoundByPosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getColumn
     */
    public function testGetColumnThrowsColumnNotFoundByHeaderCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getCell
     * @todo   Implement testGetCell().
     */
    public function testGetCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wiakowe\CsvReader\File\CsvFile::getRowIterator
     * @todo   Implement testGetRowIterator().
     */
    public function testGetRowIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
